version: '2'

services:
  postgres:
    # image: 'postgres:9.5'
    # environment:
    #   POSTGRES_USER: 'guestbook'
    #   POSTGRES_PASSWORD: 'Nfz98ukfki7Df2UbV8H'
    # ports:
    #   - '5432:5432'
    # volumes:
    #   - 'postgres:/var/lib/postgresql/data'
    # env_file:
    # - 'config/database.yml'
    image: postgres:9.5
    environment:
      POSTGRES_USER: "guestbook"
      POSTGRES_PASSWORD: "Nfz98ukfki7Df2UbV8H"
      POSTGRES_DB: "guestbook"
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    # health_check:
    #     test: ["CMD", "curl", "-f", "http://localhost:5432"]
    #     interval: 30s
    #     timeout: 10s
    #     retries: 5
    # test: ["CMD", "ping", "-c","1", "localhost:5432"]
    # command: bash -c "sleep 10;"

  redis:
    image: 'redis:3.2-alpine'
    # command: redis-server --requirepass yourpassword
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'

  website:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    command: bash -c "sleep 10 && bundle install && rake db:migrate && puma -p 3000"
    ports:
      - '3000:3000'
    links:
      - postgres
    # volumes:
    #   - '.:/app/guestbook'
    env_file:
      - '.env'
    tty: true
    environment:
      DATABASE_URL: postgres://guestbook:Nfz98ukfki7Df2UbV8H@postgres/guestbook
      REDIS_HOST: redis
      RAILS_ENV: development

volumes:
  redis:
  postgres: